version: "3"

services:
  e2l_as_broker:
    hostname: e2l-as-broker
    image: e2l-as-broker:v1.0.0
    ports:
      - "10884:1883"
    volumes:
      - ./e2l-as-broker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./e2l-as-broker/data/:/mosquitto/data/
      - ./e2l-as-broker/log/:/mosquitto/log/
    networks:
      - e2l_network

  e2l_sink:
    hostname: e2l-sink1
    image: e2l-sink:v1.0.0
    depends_on:
      - e2l_as_broker
    volumes:
      - ./e2l-sink/device_files/:/home/e2l/e2l-sink/device_files/
    env_file:
      - ".env.sink"
    ports:
      - "50051:50051"
    networks:
      - e2l_network

  e2l_process:
    hostname: e2l-process-sink
    image: ghcr.io/edge2lora/e2l-process:time-window-handover-test1
    depends_on:
      - e2l_as_broker
    env_file:
      - ".env.process"
    networks:
      - e2l_network

networks:
  e2l_network:
    name: e2l_network
    driver: overlay
