# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import e2gw_rpc_client.edge2gateway_pb2 as edge2gateway__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edge2gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class Edge2GatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.handle_ed_pub_info = channel.unary_unary(
                '/edge2gateway.Edge2Gateway/handle_ed_pub_info',
                request_serializer=edge2gateway__pb2.EdPubInfo.SerializeToString,
                response_deserializer=edge2gateway__pb2.GwInfo.FromString,
                _registered_method=True)
        self.remove_e2device = channel.unary_unary(
                '/edge2gateway.Edge2Gateway/remove_e2device',
                request_serializer=edge2gateway__pb2.E2LDeviceInfo.SerializeToString,
                response_deserializer=edge2gateway__pb2.E2LData.FromString,
                _registered_method=True)
        self.add_devices = channel.unary_unary(
                '/edge2gateway.Edge2Gateway/add_devices',
                request_serializer=edge2gateway__pb2.E2LDevicesInfoComplete.SerializeToString,
                response_deserializer=edge2gateway__pb2.GwResponse.FromString,
                _registered_method=True)
        self.set_active = channel.unary_unary(
                '/edge2gateway.Edge2Gateway/set_active',
                request_serializer=edge2gateway__pb2.ActiveFlag.SerializeToString,
                response_deserializer=edge2gateway__pb2.GwResponse.FromString,
                _registered_method=True)


class Edge2GatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def handle_ed_pub_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remove_e2device(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_devices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_active(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Edge2GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'handle_ed_pub_info': grpc.unary_unary_rpc_method_handler(
                    servicer.handle_ed_pub_info,
                    request_deserializer=edge2gateway__pb2.EdPubInfo.FromString,
                    response_serializer=edge2gateway__pb2.GwInfo.SerializeToString,
            ),
            'remove_e2device': grpc.unary_unary_rpc_method_handler(
                    servicer.remove_e2device,
                    request_deserializer=edge2gateway__pb2.E2LDeviceInfo.FromString,
                    response_serializer=edge2gateway__pb2.E2LData.SerializeToString,
            ),
            'add_devices': grpc.unary_unary_rpc_method_handler(
                    servicer.add_devices,
                    request_deserializer=edge2gateway__pb2.E2LDevicesInfoComplete.FromString,
                    response_serializer=edge2gateway__pb2.GwResponse.SerializeToString,
            ),
            'set_active': grpc.unary_unary_rpc_method_handler(
                    servicer.set_active,
                    request_deserializer=edge2gateway__pb2.ActiveFlag.FromString,
                    response_serializer=edge2gateway__pb2.GwResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edge2gateway.Edge2Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Edge2Gateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def handle_ed_pub_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edge2gateway.Edge2Gateway/handle_ed_pub_info',
            edge2gateway__pb2.EdPubInfo.SerializeToString,
            edge2gateway__pb2.GwInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def remove_e2device(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edge2gateway.Edge2Gateway/remove_e2device',
            edge2gateway__pb2.E2LDeviceInfo.SerializeToString,
            edge2gateway__pb2.E2LData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_devices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edge2gateway.Edge2Gateway/add_devices',
            edge2gateway__pb2.E2LDevicesInfoComplete.SerializeToString,
            edge2gateway__pb2.GwResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_active(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edge2gateway.Edge2Gateway/set_active',
            edge2gateway__pb2.ActiveFlag.SerializeToString,
            edge2gateway__pb2.GwResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
