apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-devices
  namespace: edge2lora
  labels:
    volume: "devices-volume"
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/milux/Developer/phd/e2l/e2l-as/e2l-sink/device_files"
  storageClassName: "standard"