apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: edge2lora
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1 
  template:
    metadata:
      labels:
        app: db # has to match .spec.selector.matchLabels
    spec:
      # nodeSelector:
      #   machine-as: "yes"
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: mongodb/mongodb-enterprise-server:7.0-ubuntu2204
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: edge2lora
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - name: db
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: db-headless-svc
  namespace: edge2lora
spec:
  clusterIP: None
  selector:
    app: db
  ports:
  - name: db
    port: 27017
    targetPort: 27017